# Generated by Django 5.1.3 on 2024-12-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0003_alter_turfadmin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turfadmin',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
