# Generated by Django 5.1.3 on 2024-12-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0004_alter_turfadmin_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='turfadmin',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='turfadmin',
            name='ownername',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
