# Generated by Django 5.1.3 on 2024-12-14 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0005_turfadmin_location_turfadmin_ownername'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(blank=True, max_length=250, null=True)),
                ('category', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('price', models.FloatField(blank=True, null=True)),
                ('quantity', models.CharField(blank=True, max_length=250, null=True)),
                ('availablequantity', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(default=True, max_length=50)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Ownerid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('turfid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turf.turfadmin')),
            ],
        ),
    ]
