# Generated by Django 5.1.3 on 2024-12-26 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0006_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='availablequantity',
        ),
        migrations.AddField(
            model_name='turfadmin',
            name='closingtime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='turfadmin',
            name='openingtime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='turfadmin',
            name='rent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeslot', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(default=False, max_length=50)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('turfid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turf.turfadmin')),
            ],
        ),
    ]
